### ISSUE TITLE
Coins very difficult to collect

### ISSUE THREAD

**Issue by BarthdryZ** [BuckarooBanzay/super_sam#31] opened 2022-02-25 07:37 UTC
Actually i just noticed that in some cases even though the pointer points towards the coin and i move towards it. it does not get collected.

**Comment by BuckarooBanzay** [comment] 2022-02-25 09:05
The coin should disappear as soon as you are 1.5 nodes away from it :/
Can you describe your setup? (operating system, minetest-version, lua/luajit?)
Do you experience lag-issues? (`/status` output from that moment would be nice)
Is that something that happens all the time or just sometimes?

Thanks for the bug report btw :+1:

Relevant code here:
https://github.com/BuckarooBanzay/super_sam/blob/15c732f385a3ff9c70848eb50e23ab3a9c37932f/mods/super_sam/itempickup.lua#L5-L22

**Comment by BuckarooBanzay** [comment] 2023-06-02 15:35
Can't reproduce, closing

**Closed by BuckarooBanzay** 2023-06-02 15:35 UTC
Labels: bug
